name: AUP
version: 0.1.3
main: io.papermc.aup.Main
description: Among Us Plugin
author: pairnon
contributors: [enlxmfflsdis34, kionmanesh, Quitous, clkefe]
website: https://github.com/Among-Us-Plugin
api-version: '1.20'
commands:
  startgame:
    description: Start the Among Us game
    usage: /startgame
  endgame:
    description: End the Among Us game
    usage: /endgame
  impostors:
    description: Set number of impostors per game
    usage: /impostors <amount>
  cooldown:
    description: Configure cooldown durations
    usage: /cooldown <action> <seconds>
  tasks:
    description: Configure task win threshold
    usage: /tasks <amount>
  meetingduration:
    description: Configure meeting duration
    usage: /meetingduration <seconds>