name: AUP
version: 1.0.0
main: io.papermc.aup.Main
description: Among Us Plugin
author: pairnon
contributors: [enlxmfflsdis34, kionmanesh, Quitous, SuleymanEfe]
website: https://github.com/pairnon/AU-Plugin
api-version: '1.20'
commands:
  startgame:
    description: Start the Among Us game
    usage: /startgame
  endgame:
    description: End the Among Us game
    usage: /endgame
  crewmateswin:
    description: Admin command - force the game to crewmate victory
    usage: /crewmateswin
  impostorswin:
    description: Admin command - force the game to impostor victory
    usage: /impostorswin